#!/bin/bash
# vim: ts=4 sw=4 noet

# Get the user name by UID
# Search for the user with UID from 1000 to 1010
# Use the first one found
for i in {1000..1010}; do
	USER=$(id -nu "$i")
	if [[ -n $USER ]]; then
		break
	fi
done

SETTINGS_DIR="/home/${USER}/.config/udev_hotplug/"

if [[ -d "${SETTINGS_DIR}" ]]; then
	rm -rf "${SETTINGS_DIR}"
	echo "Removed: ${SETTINGS_DIR}"
	echo
fi

sudo service udev restart
sudo systemctl restart acpid
